'use client';
import { BarChart3, Trophy, Flame, Target, Book, Award, Calendar, TrendingUp } from 'lucide-react';
import { useProgress } from '@/hooks/useProgress';
import { lawsData } from '@/data/lawsData';
import { useExamHistory } from '@/hooks/useExamHistory';
import { useEffect, useState } from 'react';

export default function ProgressPage() {
  const {isLoaded,getProgress,getTotalProgress,streak}=useProgress();
  const {records}=useExamHistory();
  const [daily,setDaily]=useState<Record<string,number>>({});
  useEffect(()=>{queueMicrotask(()=>{try{setDaily(JSON.parse(localStorage.getItem('app_progress')||'{}').dailyCounts||{});}catch{}});},[isLoaded]);
  if(!isLoaded)return <div className="p-10 text-center text-tertiary">載入中…</div>;
  const totalPct=getTotalProgress();let totalRead=0,totalAll=0;lawsData.forEach(l=>{const p=getProgress(l.id);totalRead+=p.read;totalAll+=p.total;});
  const days=Array.from({length:14},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(13-i));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;});
  const maxV=Math.max(1,...days.map(d=>daily[d]||0));
  const achievements=[{id:'first',label:'初學者',need:totalRead>=1,desc:'完成第 1 條',emoji:'🌱'},{id:'ten',label:'起步',need:totalRead>=10,desc:'累積 10 條',emoji:'🚀'},{id:'streak3',label:'三日連續',need:streak>=3,desc:'連續 3 天',emoji:'🔥'},{id:'streak7',label:'一週不輟',need:streak>=7,desc:'連續 7 天',emoji:'🏅'},{id:'half',label:'半程攻略',need:totalPct>=50,desc:'總進度 50%',emoji:'🗺️'},{id:'exam',label:'首測完成',need:records.length>=1,desc:'完成一次模測',emoji:'🎯'}];
  const stats=[{label:'總進度',value:`${totalPct}%`,icon:Target,accent:'text-indigo-600'},{label:'已讀法條',value:`${totalRead}/${totalAll}`,icon:Book,accent:'text-sky-600'},{label:'連續學習',value:`${streak} 天`,icon:Flame,accent:'text-orange-500'},{label:'已解鎖成就',value:`${achievements.filter(a=>a.need).length}/${achievements.length}`,icon:Trophy,accent:'text-amber-500'}];
  return <div className="page-shell max-w-5xl space-y-5">
    <header className="page-header flex items-start gap-4"><div className="w-11 h-11 rounded-2xl bg-indigo-500/10 text-indigo-600 flex items-center justify-center"><BarChart3 size={20}/></div><div><div className="text-[10px] font-black tracking-[.16em] text-indigo-600">LEARNING ANALYTICS</div><h1 className="text-2xl font-black mt-1 text-primary">學習進度</h1><p className="text-sm mt-1 text-secondary">目前以本機進度為準；Supabase 同步功能尚未全面啟用。</p></div></header>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{stats.map(s=><div key={s.label} className="card rounded-2xl p-4"><div className="flex items-center gap-1.5 text-[10px] font-bold text-tertiary"><s.icon size={13} className={s.accent}/>{s.label}</div><div className="text-2xl font-black mt-2 text-primary">{s.value}</div>{s.label==='總進度'&&<div className="mt-3 h-1.5 progress-track rounded-full overflow-hidden"><div className="h-full bg-indigo-600 rounded-full" style={{width:`${totalPct}%`}}/></div>}</div>)}</div>
    <section className="card rounded-[1.35rem] p-5"><h2 className="text-sm font-black text-primary flex items-center gap-2"><TrendingUp size={15} className="text-indigo-600"/>近 14 日學習曲線</h2><div className="mt-5 h-28 flex items-end gap-1.5">{days.map(d=>{const v=daily[d]||0,h=Math.max(3,Math.round(v/maxV*96));return <div key={d} className="flex-1 flex flex-col items-center gap-1"><div className="w-full rounded-t-md bg-indigo-600/85" style={{height:`${h}px`,opacity:v?1:.12}} title={`${d}: ${v}條`}/><span className="text-[8px] text-tertiary hidden sm:block">{d.slice(8)}</span></div>;})}</div><p className="text-[10px] mt-3 text-tertiary">柱高代表當日完成條數，空白日保留最低高度方便辨識。</p></section>
    <section className="card rounded-[1.35rem] p-5"><h2 className="text-sm font-black text-primary flex items-center gap-2"><Award size={15} className="text-amber-500"/>成就解鎖</h2><div className="grid grid-cols-2 md:grid-cols-3 gap-3 mt-4">{achievements.map(a=><div key={a.id} className={`rounded-2xl p-3 border ${a.need?'bg-amber-500/[0.07] border-amber-500/20':'surface opacity-70'}`}><div className="text-2xl">{a.need?a.emoji:'🔒'}</div><div className="text-sm font-black mt-2 text-primary">{a.label}</div><div className="text-[10px] mt-0.5 text-tertiary">{a.desc}</div></div>)}</div></section>
    <section className="card rounded-[1.35rem] p-5"><h2 className="text-sm font-black text-primary">各科詳細進度</h2><div className="space-y-3 mt-4">{lawsData.map(l=>{const p=getProgress(l.id);return <div key={l.id} className="grid grid-cols-[7rem_1fr_auto] items-center gap-3"><span className="text-xs font-bold truncate text-secondary">{l.name}</span><div className="h-2 progress-track rounded-full overflow-hidden"><div className="h-full bg-indigo-600 rounded-full" style={{width:`${p.percentage}%`}}/></div><span className="text-[10px] font-black text-tertiary w-12 text-right">{p.percentage}%</span></div>;})}</div></section>
    <section className="card rounded-[1.35rem] p-5"><h2 className="text-sm font-black text-primary flex items-center gap-2"><Calendar size={15} className="text-emerald-600"/>測驗紀錄</h2>{records.length===0?<p className="text-xs mt-3 text-tertiary">尚無紀錄。完成題庫測驗後，分數會顯示在這裡。</p>:<div className="mt-3 divide-y" style={{borderColor:'var(--border)'}}>{records.slice(0,10).map(r=><div key={r.id} className="py-3 flex items-center justify-between gap-3 text-xs"><span className="text-secondary">{new Date(r.date).toLocaleString('zh-TW')} · {r.mode}</span><span className={`font-black ${r.score/r.total>=.6?'text-emerald-600':'text-amber-600'}`}>{r.score}/{r.total} · {Math.round(r.score/r.total*100)}%</span></div>)}</div>}</section>
  </div>;
}
