import fs from 'fs';
import path from 'path';

const lawsDir = path.resolve(process.cwd(), '..', '..', '07_原始法規');
const outPath = path.resolve(process.cwd(), 'src/data/generatedArticles.ts');

const fileMap: Record<string, string> = {
  '民法.md': 'civil',
  '土地法.md': 'land',
  '平均地權條例.md': 'equal_land',
  '土地稅法.md': 'land_tax',
  '房屋稅條例.md': 'house_tax',
  '契稅條例.md': 'deed_tax',
  '不動產經紀業管理條例.md': 'broker',
  '消費者保護法.md': 'consumer',
  '公平交易法.md': 'fair_trade',
  '不動產估價技術規則.md': 'appraisal',
  '土地徵收條例.md': 'land_expropriation',
  '公寓大廈管理條例.md': 'apartment',
};

type Art = { lawId: string; articleNumber: string; text: string };

const articleStart = /^第\s*([0-9]+(?:-[0-9]+)?)\s*條\s*(.*)$/;
const structuralHeading = /^第\s*[一二三四五六七八九十百千]+\s*(編|章|節|款|目)(?:\s|$)/;

function normalizeArticle(articleNumber: string, parts: string[]) {
  const body = parts
    .map(line => line.trim())
    .filter(Boolean)
    .filter(line => !structuralHeading.test(line))
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
  return `第 ${articleNumber} 條${body ? body : ''}`;
}

function parseFile(filePath: string, lawId: string): Art[] {
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  const arts: Art[] = [];
  let current: { articleNumber: string; parts: string[] } | null = null;

  const flush = () => {
    if (!current) return;
    const text = normalizeArticle(current.articleNumber, current.parts);
    if (text.length > 5) arts.push({ lawId, articleNumber: current.articleNumber, text });
    current = null;
  };

  for (const rawLine of lines) {
    const line = rawLine.trim();
    const match = line.match(articleStart);
    if (match) {
      flush();
      current = { articleNumber: match[1], parts: [match[2]] };
      continue;
    }
    if (!current || !line || structuralHeading.test(line)) continue;
    current.parts.push(line);
  }
  flush();
  return arts;
}

const all: Art[] = [];
for (const [fileName, lawId] of Object.entries(fileMap)) {
  const fp = path.join(lawsDir, fileName);
  if (!fs.existsSync(fp)) {
    console.warn('missing', fileName);
    continue;
  }
  const arts = parseFile(fp, lawId);
  console.log(lawId, arts.length);
  all.push(...arts);
}

const grouped: Record<string, { articleNumber: string; text: string }[]> = {};
for (const a of all) {
  if (!grouped[a.lawId]) grouped[a.lawId] = [];
  grouped[a.lawId].push({ articleNumber: a.articleNumber, text: a.text });
}

const duplicates = all.filter((article, index) => all.findIndex(x => x.lawId === article.lawId && x.articleNumber === article.articleNumber) !== index);
if (duplicates.length) throw new Error(`Duplicate article ids: ${duplicates.map(x => `${x.lawId}-${x.articleNumber}`).join(', ')}`);

const contaminated = all.filter(article => /第\s*[一二三四五六七八九十百千]+\s*(編|章|節|款|目)(?:\s|$)/.test(article.text));
if (contaminated.length) throw new Error(`Structural headings leaked into ${contaminated.length} articles`);

const out = `// AUTO-GENERATED by src/scripts/parseLaws.ts — do not edit manually\n// Source: 07_原始法規/*.md\nexport const generatedArticles: Record<string, { articleNumber: string; text: string }[]> = ${JSON.stringify(grouped, null, 2)};\nexport const generatedArticlesFlat: { lawId: string; articleNumber: string; text: string }[] = ${JSON.stringify(all, null, 2)};\n`;
fs.writeFileSync(outPath, out, 'utf8');
console.log(`Wrote ${all.length} clean articles to ${outPath}`);
