import fs from 'fs';
import path from 'path';

const lawsDir = path.resolve(process.cwd(), '..', '..', '07_原始法規');
const outPath = path.resolve(process.cwd(), 'src/data/generatedArticles.ts');

const fileMap: Record<string, string> = {
  '民法.md': 'civil',
  '土地法.md': 'land',
  '平均地權條例.md': 'equal_land',
  '土地稅法.md': 'land_tax',
  '房屋稅條例.md': 'house_tax',
  '契稅條例.md': 'deed_tax',
  '不動產經紀業管理條例.md': 'broker',
  '消費者保護法.md': 'consumer',
  '公平交易法.md': 'fair_trade',
  '不動產估價技術規則.md': 'appraisal',
};

type Art = { lawId: string; articleNumber: string; text: string };

function parseFile(filePath: string, lawId: string): Art[] {
  const content = fs.readFileSync(filePath, 'utf8');
  // Match "第 X 條" patterns, capturing number like 30-1, 34-1
  const regex = /第\s*([0-9]+(?:-[0-9]+)?)\s*條/g;
  const indices: { num: string; index: number }[] = [];
  let m: RegExpExecArray | null;
  while ((m = regex.exec(content)) !== null) {
    indices.push({ num: m[1], index: m.index });
  }
  const arts: Art[] = [];
  for (let i = 0; i < indices.length; i++) {
    const start = indices[i].index;
    const end = i + 1 < indices.length ? indices[i+1].index : content.length;
    // Extract from "第 X 條" to next "第 Y 條"
    let slice = content.slice(start, end).trim();
    // Clean up: remove leading "第 X 條" label duplication, keep as text
    // First line is title, rest is body
    slice = slice.replace(/\s+/g, ' ').trim();
    // Keep reasonable length
    if (slice.length > 5) arts.push({ lawId, articleNumber: indices[i].num, text: slice });
  }
  return arts;
}

const all: Art[] = [];
for (const [fileName, lawId] of Object.entries(fileMap)) {
  const fp = path.join(lawsDir, fileName);
  if (!fs.existsSync(fp)) { console.warn('missing', fileName); continue; }
  const arts = parseFile(fp, lawId);
  console.log(lawId, arts.length);
  all.push(...arts);
}

const grouped: Record<string, {articleNumber:string;text:string}[]> = {};
for (const a of all) {
  if (!grouped[a.lawId]) grouped[a.lawId] = [];
  grouped[a.lawId].push({ articleNumber: a.articleNumber, text: a.text });
}

const out = `// AUTO-GENERATED by src/scripts/parseLaws.ts — do not edit manually
// Source: 07_原始法規/*.md
export const generatedArticles: Record<string, { articleNumber: string; text: string }[]> = ${JSON.stringify(grouped, null, 2)};
export const generatedArticlesFlat: { lawId: string; articleNumber: string; text: string }[] = ${JSON.stringify(all, null, 2)};
`;

fs.writeFileSync(outPath, out, 'utf8');
console.log(`Wrote ${all.length} articles to ${outPath}`);
