'use client';
import { useMemo, useState } from 'react';
import { PencilRuler, RotateCcw, Check, X, SlidersHorizontal, Target, Sparkles } from 'lucide-react';
import { examQuestions } from '@/data/examData';
import { useExamHistory } from '@/hooks/useExamHistory';

type Mode='all'|'easy'|'medium'|'hard'|'civil'|'land'|'broker';
const labels:Record<Mode,string>={all:'全部試題',easy:'簡單',medium:'中等',hard:'困難',civil:'民法',land:'土地法',broker:'經紀法規'};

export default function ExamsIndex(){
  const [mode,setMode]=useState<Mode>('all');const [started,setStarted]=useState(false);const [idx,setIdx]=useState(0);const [selected,setSelected]=useState<number|null>(null);const [show,setShow]=useState(false);const [score,setScore]=useState(0);const {add}=useExamHistory();
  const pool=useMemo(()=>{if(mode==='all')return examQuestions;if(mode==='easy')return examQuestions.filter(q=>q.difficulty===1);if(mode==='medium')return examQuestions.filter(q=>q.difficulty===2);if(mode==='hard')return examQuestions.filter(q=>q.difficulty===3);return examQuestions.filter(q=>q.lawId===mode);},[mode]);
  const restart=()=>{setStarted(false);setIdx(0);setSelected(null);setShow(false);setScore(0);};
  if(!started)return <div className="page-shell max-w-5xl space-y-5">
    <header className="page-header flex items-start gap-4"><div className="w-11 h-11 rounded-2xl bg-rose-500/10 text-rose-600 flex items-center justify-center"><PencilRuler size={20}/></div><div><div className="text-[10px] font-black tracking-[.16em] text-rose-600">QUESTION BANK</div><h1 className="text-2xl font-black mt-1 text-primary">題庫中心</h1><p className="text-sm mt-1 text-secondary">先依難度暖身，再進入法規分類。每題作答後立即顯示解析。</p></div></header>
    <section className="card rounded-[1.4rem] p-5"><div className="flex items-center gap-2 text-sm font-black text-primary"><SlidersHorizontal size={16} className="text-indigo-600"/>選擇測驗模式</div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-4">{(Object.keys(labels) as Mode[]).map(m=><button key={m} onClick={()=>setMode(m)} className={`px-3 py-3 rounded-xl text-sm font-black border transition ${mode===m?'bg-indigo-600 text-white border-indigo-600':'surface text-secondary'}`}>{labels[m]}</button>)}</div><div className="mt-4 surface rounded-2xl p-4 flex items-center justify-between gap-4"><div><div className="text-[10px] font-black text-tertiary">目前題量</div><div className="text-2xl font-black mt-1 text-primary">{pool.length}<span className="text-xs ml-1 text-tertiary">題</span></div></div><div className="text-right"><div className="text-[10px] font-black text-tertiary">建議時間</div><div className="text-sm font-black mt-1 text-primary">{pool.length<=7?'約 10':'約 20'} 分鐘</div></div></div><button onClick={()=>pool.length&&setStarted(true)} disabled={!pool.length} className="mt-4 w-full bg-indigo-600 hover:bg-indigo-700 disabled:opacity-40 text-white font-black py-3.5 rounded-xl transition">開始測驗</button>{!pool.length&&<p className="text-xs text-amber-600 mt-2">此分類暫無題目，請換一個模式。</p>}</section>
    <section className="card rounded-[1.4rem] p-5"><div className="text-sm font-black text-primary flex items-center gap-2"><Sparkles size={15} className="text-amber-500"/>建議節奏</div><div className="grid md:grid-cols-3 gap-3 mt-3">{[['🌱','第一輪','先做簡單題，確認有看懂'],['🎯','第二輪','切換中等與單科分類'],['⚠️','考前','困難題集中抓陷阱']].map(([e,t,d])=><div key={t} className="surface rounded-2xl p-3"><div className="text-xl">{e}</div><div className="text-xs font-black mt-2 text-primary">{t}</div><div className="text-[10px] mt-1 text-tertiary">{d}</div></div>)}</div></section>
  </div>;

  if(idx>=pool.length)return <div className="page-shell max-w-2xl"><div className="card rounded-[1.5rem] p-8 text-center mt-10"><div className="w-16 h-16 rounded-2xl bg-emerald-500/10 text-emerald-600 flex items-center justify-center mx-auto"><Target size={28}/></div><h1 className="text-2xl font-black mt-4 text-primary">完成 {labels[mode]}</h1><div className="text-5xl font-black text-indigo-600 mt-4">{score}<span className="text-lg text-tertiary">/{pool.length}</span></div><div className="text-sm mt-2 text-secondary">正確率 {pool.length?Math.round(score/pool.length*100):0}%</div><button onClick={restart} className="mt-6 surface rounded-xl px-6 py-3 text-sm font-black text-primary inline-flex items-center gap-2"><RotateCcw size={15}/>再測一次</button></div></div>;

  const q=pool[idx];
  const pick=(i:number)=>{if(show)return;setSelected(i);setShow(true);if(i===q.answer)setScore(s=>s+1);};
  const next=()=>{if(idx<pool.length-1){setIdx(i=>i+1);setSelected(null);setShow(false);}else{add({id:Date.now().toString(),date:new Date().toISOString(),mode:labels[mode],score,total:pool.length});setIdx(pool.length);}};
  return <div className="page-shell max-w-3xl space-y-4">
    <div className="flex items-center justify-between text-xs font-black text-tertiary"><span>{labels[mode]}</span><span>{idx+1}/{pool.length} · {score} 分</span></div><div className="h-1.5 progress-track rounded-full overflow-hidden"><div className="h-full bg-indigo-600 rounded-full" style={{width:`${((idx+1)/pool.length)*100}%`}}/></div>
    <section className="card rounded-[1.5rem] p-6 md:p-7"><div className="flex flex-wrap gap-2"><span className="surface rounded-full px-2.5 py-1 text-[10px] font-bold text-tertiary">{q.year}</span><span className="surface rounded-full px-2.5 py-1 text-[10px] font-bold text-tertiary">{labels[q.lawId as Mode]||q.lawId}</span></div><h2 className="text-lg md:text-xl font-black mt-4 leading-relaxed text-primary">{q.question}</h2><div className="space-y-2.5 mt-5">{q.options.map((opt,i)=>{const correct=show&&i===q.answer,wrong=show&&selected===i&&i!==q.answer;return <button key={i} onClick={()=>pick(i)} disabled={show} className={`w-full text-left p-3.5 rounded-xl border flex items-center justify-between gap-3 text-sm font-bold transition ${correct?'bg-emerald-500/10 border-emerald-500/30 text-emerald-700 dark:text-emerald-300':wrong?'bg-rose-500/10 border-rose-500/30 text-rose-600 dark:text-rose-300':'surface text-secondary hover:border-indigo-300'}`}><span>{String.fromCharCode(65+i)}. {opt}</span>{correct&&<Check size={16}/>} {wrong&&<X size={16}/>}</button>;})}</div>{show&&<div className="mt-5 surface rounded-2xl p-4"><div className="text-[10px] font-black text-indigo-600">解析</div><p className="text-sm leading-relaxed mt-1 text-secondary">{q.explanation}</p><button onClick={next} className="mt-4 w-full bg-indigo-600 text-white py-3 rounded-xl text-sm font-black">{idx===pool.length-1?'完成測驗':'下一題'}</button></div>}</section>
  </div>;
}
