'use client';
import { useState } from 'react';
import { Bot, Send, User, Loader2, Sparkles, KeyRound } from 'lucide-react';
import { getStoredGeminiKey } from '@/lib/geminiKey';
import Link from 'next/link';

type Msg={role:'ai'|'user';content:string};
export default function AITeacher(){
  const [messages,setMessages]=useState<Msg[]>([{role:'ai',content:'你好，我是你的不動產經紀人 AI 家教。可以直接用白話問問題，我會先講重點，再用案例拆解。'}]);
  const [input,setInput]=useState(''); const [loading,setLoading]=useState(false);
  const send=async(q:string)=>{if(!q.trim()||loading)return;const text=q.trim();setMessages(v=>[...v,{role:'user',content:text}]);setInput('');setLoading(true);try{const res=await fetch('/api/ai/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({articleText:'',question:text,lawName:'',articleId:'',apiKey:getStoredGeminiKey()||undefined})});const j=await res.json();setMessages(v=>[...v,{role:'ai',content:j.reply||j.error||'目前沒有回覆'}]);}catch{setMessages(v=>[...v,{role:'ai',content:'連線失敗，請稍後再試。'}]);}finally{setLoading(false);}};
  return <div className="h-[calc(100dvh-70px)] md:h-dvh flex flex-col max-w-5xl mx-auto">
    <header className="m-4 md:m-6 mb-0 page-header !rounded-[1.4rem] flex items-center justify-between gap-4 shrink-0"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-2xl bg-indigo-600 text-white flex items-center justify-center"><Bot size={20}/></div><div><div className="flex items-center gap-2"><h1 className="text-lg font-black text-primary">AI 老師</h1><span className="status-current release-status">Gemini</span></div><p className="text-xs mt-0.5 text-tertiary">法條資料與 AI 解釋分離，避免 AI 改寫正式條文。</p></div></div><Link href="/settings" className="hidden sm:flex items-center gap-1.5 text-xs font-black text-indigo-600"><KeyRound size={13}/>API 設定</Link></header>
    <main className="flex-1 min-h-0 overflow-y-auto p-4 md:p-6 space-y-4">{messages.map((m,i)=><div key={i} className={`flex gap-2.5 max-w-3xl ${m.role==='user'?'ml-auto flex-row-reverse':''}`}><div className={`w-8 h-8 rounded-xl flex items-center justify-center shrink-0 ${m.role==='user'?'surface text-secondary':'bg-indigo-500/10 text-indigo-600'}`}>{m.role==='user'?<User size={14}/>:<Bot size={14}/>}</div><div className={`max-w-[86%] rounded-2xl px-4 py-3 text-sm leading-relaxed whitespace-pre-wrap ${m.role==='user'?'bg-indigo-600 text-white rounded-tr-sm':'card rounded-tl-sm text-secondary'}`}>{m.role==='ai'&&<div className="text-[10px] font-black text-indigo-600 flex items-center gap-1 mb-1.5"><Sparkles size={11}/>老師整理</div>}{m.content}</div></div>)}{loading&&<div className="flex items-center gap-2 text-xs text-tertiary"><Loader2 size={14} className="animate-spin"/>老師正在整理重點…</div>}</main>
    <footer className="shrink-0 p-4 md:p-6 pt-2 pb-24 md:pb-6"><form onSubmit={e=>{e.preventDefault();void send(input);}} className="card rounded-2xl p-2 flex items-end gap-2"><textarea value={input} onChange={e=>setInput(e.target.value)} rows={1} placeholder="直接問：民法第 758 條沒登記會怎樣？" className="flex-1 bg-transparent resize-none outline-none px-3 py-2 text-sm text-primary placeholder:text-tertiary"/><button disabled={loading||!input.trim()} className="w-10 h-10 rounded-xl bg-indigo-600 text-white flex items-center justify-center disabled:opacity-40">{loading?<Loader2 size={16} className="animate-spin"/>:<Send size={16}/>}</button></form><div className="mt-2 flex gap-1.5 overflow-x-auto">{['用最白話講民法758','比較767和184','出3題土地法選擇題'].map(s=><button key={s} onClick={()=>setInput(s)} className="surface rounded-full px-3 py-1.5 text-[10px] font-bold text-secondary whitespace-nowrap">{s}</button>)}</div></footer>
  </div>;
}
